# Generated by Django 4.1.3 on 2022-12-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Saisis ton prénom', max_length=30)),
                ('input', models.CharField(help_text='Pose ta question', max_length=150)),
                ('response', models.TextField(max_length=10000)),
            ],
        ),
    ]
